import {Injectable} from '@angular/core';
import {Subject} from 'rxjs/Subject';
import {Card} from '../../model/card';

@Injectable()
export class CardsService {

  cardsChanged: Subject<Card[]> = new Subject<Card[]>();
  cardsSelectedChanged: Subject<Card[]> = new Subject<Card[]>();
  selectedCards: Card[] = [];

  constructor() {
  }

  cards: Card[] = [
    new Card('name', true, '../../../assets/Screenshot_20180220-214911_1.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214856_1.jpg', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ai.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214755_1.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214811_1.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214844_1.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214918_1.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214903_1.jpg', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214918_2.jpg', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/galaxy.jpg', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/ajith.png', false),
    new Card('name', true, '../../../assets/amazon.png', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/dhoni.jpg', false),
    new Card('name', true, '../../../assets/Screenshot_20180220-214851_1.jpg', false)
  ];

  getCards() {
    return this.cards;
  }

  resetSelectedCards() {
    this.selectedCards = [];
  }

  resetCards() {
    this.cards = [
      new Card('name', true, '../../../assets/Screenshot_20180220-214911_1.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214856_1.jpg', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ai.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214755_1.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214811_1.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214844_1.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214918_1.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214903_1.jpg', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214918_2.jpg', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/galaxy.jpg', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/ajith.png', false),
      new Card('name', true, '../../../assets/amazon.png', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/dhoni.jpg', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214851_1.jpg', false)
    ];
  }

  updateClicked(index: number) {
    this.cards[index].isClicked = true;
    this.cardsChanged.next(this.cards.slice());
  }

  cardSelected(index: number) {
    this.selectedCards.push(this.cards[index]);
    this.cardsSelectedChanged.next(this.selectedCards.slice());
  }

}


/*new Card('name', true, '../../../assets/Screenshot_20180220-214911_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214856_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/ai.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214755_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214811_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214844_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214918_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214903_1.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214918_2.jpg', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', false, '', false),
      new Card('name', true, '../../../assets/Screenshot_20180220-214851_1.jpg', false)*/
